### ISSUE TITLE
npm install giving errors

### ISSUE THREAD

**Issue by sim4life** [eddyerburgh/parcel-vuejs-template#4]
After creating the Vue project, I navigate to the directory and run
`$ npm install`

and it gives the following errors:

npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > fsevents@1.1.3 install /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/fsevents
npm ERR! prepareGitDep > node install
npm ERR! prepareGitDep
npm ERR! prepareGitDep [fsevents] Success: "/Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm ERR! prepareGitDep
npm ERR! prepareGitDep > husky@0.14.3 install /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/husky
npm ERR! prepareGitDep > node ./bin/install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep husky
npm ERR! prepareGitDep setting up Git hooks
npm ERR! prepareGitDep done
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > node-sass@4.7.2 install /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep Cached binary found at /Users/username/.npm/node-sass/4.7.2/darwin-x64-59_binding.node
npm ERR! prepareGitDep
npm ERR! prepareGitDep > node-sass@4.7.2 postinstall /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/build.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep Binary found at /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b/node_modules/node-sass/vendor/darwin-x64-59/binding.node
npm ERR! prepareGitDep Testing binary
npm ERR! prepareGitDep Binary is fine
npm ERR! prepareGitDep
npm ERR! prepareGitDep > parcel-bundler@1.4.1 postinstall /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b
npm ERR! prepareGitDep > node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"
npm ERR! prepareGitDep
npm ERR! prepareGitDep Love Parcel? You can now donate to our open collective:
npm ERR! prepareGitDep  > https://opencollective.com/parcel/donate
npm ERR! prepareGitDep
npm ERR! prepareGitDep > parcel-bundler@1.4.1 prepare /Users/username/.npm/_cacache/tmp/git-clone-c7b3d58b
npm ERR! prepareGitDep > yarn build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep sh: yarn: command not found
npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! parcel-bundler@1.4.1 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the parcel-bundler@1.4.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/username/.npm/_logs/2018-02-17T18_43_42_454Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: parcel-bundler@github:parcel-bundler/parcel#vue.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-02-17T18_43_42_751Z-debug.log

I don't have yarn installed and it is probably trying to run some yarn command. Can this template work with npm too?

**Comment by eddyerburgh** [comment]
This works for me with npm 5.6.0

What npm version are you running?

**Comment by sim4life** [comment]
I'm also running npm v 5.6.0

**Comment by eddyerburgh** [comment]
I can't reproduce locally. What's your OS?

**Comment by sim4life** [comment]
I'm using MacOS Sierra v10.12.6.
Can you find any clue from the error log I posted?

**Comment by eddyerburgh** [comment]
From the log, it looked like npm couldn't resolve the GitHub URL for the parcel vue branch. But it resolves correctly on my machine, and you're using the same version of npm as me, so I'm not sure what the problem is.

**Comment by eddyerburgh** [comment]
Did you resolve this issue?

**Comment by sim4life** [comment]
Sorry, I didn't work on it any further. I might try webpack4, which also provides build time improvements and all...

**Comment by eddyerburgh** [comment]
Ok, I'm going to close this because there haven't been any other users with this issue recently.

**Comment by Shashwat-A** [comment]
Am also getting the same error.
I was running npm install when I got this error:
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > husky@0.14.3 install C:\Users\Shashwat Arora\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-4b161aec\node_modules\husky
npm ERR! prepareGitDep > node ./bin/install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep husky
npm ERR! prepareGitDep setting up Git hooks
npm ERR! prepareGitDep done
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@2.6.12 postinstall C:\Users\Shashwat Arora\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-4b161aec\node_modules\core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
npm ERR! prepareGitDep > https://opencollective.com/core-js
npm ERR! prepareGitDep > https://www.patreon.com/zloirock
npm ERR! prepareGitDep
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > @react-navigation/native@3.6.5 prepare C:\Users\Shashwat Arora\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-4b161aec
npm ERR! prepareGitDep > yarn build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated react-dom@16.3.2: This version of react-dom/server contains a minor vulnerability. Please update react-dom to 16.3.3 or 16.4.2+. Learn more: https://fb.me/cve-2018-6341
npm ERR! prepareGitDep npm WARN deprecated react-navigation@2.18.3: This version of React Navigation is no longer supported. Please upgrade to at least React Navigation 4.
npm ERR! prepareGitDep npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! prepareGitDep npm WARN deprecated debug@4.1.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! prepareGitDep npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! prepareGitDep npm WARN deprecated babel-eslint@8.2.6: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! prepareGitDep npm WARN deprecated react-navigation-stack@0.7.0: This version of React Navigation Stack is no longer supported. Please upgrade to 2.x.x. See https://reactnavigation.org/docs/4.x/upgrading-from-3.x#react-navigation-stack for instructions.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! prepareGitDep npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated sane@2.5.2: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! prepareGitDep npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! prepareGitDep npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated xmldom@0.1.31: Deprecated due to CVE-2021-21366 resolved in 0.5.0
npm ERR! prepareGitDep npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! prepareGitDep 'yarn' is not recognized as an internal or external command,
npm ERR! prepareGitDep operable program or batch file.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! @react-navigation/native@3.6.5 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the @react-navigation/native@3.6.5 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Shashwat Arora\AppData\Roaming\npm-cache\_logs\2022-03-31T03_05_55_021Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

Please help
